name: autoblack_push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v1
      - run: pip install black
      - name: autoblack_push
        run: |
          black -l 127 .
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git commit -am "use black formatting" --allow-empty
          git push
